# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
