# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-18 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_duelisting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duelisting',
            options={'ordering': ('amount',)},
        ),
        migrations.AlterField(
            model_name='duelisting',
            name='debt_status',
            field=models.CharField(choices=[(b'full', b'Fully Paid'), (b'partial', b'Partially Paid'), (b'none', b'Not Paid')], default=b'none', max_length=50),
        ),
    ]
